//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportsAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRPORTS
    {
        public int IdAirport { get; set; }
        public string CodeAirport { get; set; }
        public string NameAirport { get; set; }
        public string AddressAirport { get; set; }
        public string CountryAirport { get; set; }
        public string CityAirport { get; set; }
    }
}
